# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_forum_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Forum'),
        ),
    ]
