# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180428_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='genre',
        ),
    ]
