# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_forum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='song_title',
            field=models.TextField(),
        ),
    ]
