# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20180429_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quest', to=settings.AUTH_USER_MODEL),
        ),
    ]
