# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
    ]
