# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0022_auto_20180501_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(default=1, related_name='quest', to=settings.AUTH_USER_MODEL),
        ),
    ]
