# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20180531_0520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Subject',
        ),
    ]
