# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20180531_0615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='File',
        ),
    ]
