# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_auto_20180531_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='album_title',
            new_name='name',
        ),
    ]
