# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20180531_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='album_logo',
            new_name='logo',
        ),
    ]
