# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20180531_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='album',
            new_name='subject',
        ),
    ]
