# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20180531_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='artist',
        ),
    ]
