# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_auto_20180531_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='album_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='album',
            new_name='forum',
        ),
    ]
