# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_auto_20180531_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='audio_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='audio_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='song_title',
            new_name='name',
        ),
    ]
